services:
   api:
      build:
         context: .
         dockerfile: Dockerfile
      command: python3 manage.py runserver 0.0.0.0:8000
      volumes:
         - .:/app
      ports:
         - 8000:8000
      environment:
         - DATABASE=${DATABASE}
         - PG_HOST=${PG_HOST}
         - PG_PORT=${PG_PORT}
         - SECRET_KEY=${SECRET_KEY}
         - DEBUG=${DEBUG}
         - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      restart: "always"
      depends_on:
         - postgres-db
      networks:
         - hospital-api

   postgres-db:
      image: kartoza/postgis:12.0
      expose:
         - 5432
      volumes:
         - postgres_data:/var/lib/postgresql
      environment:
         - POSTGRES_DATABASE=${POSTGRES_DATABASE}
         - POSTGRES_USER=${POSTGRES_USER}
         - POSTGRES_PASS=${POSTGRES_PASS}
         - POSTGRES_DBNAME=${POSTGRES_DBNAME}
      restart: "always"
      networks:
         - hospital-api

networks:
   hospital-api:
      driver: bridge

volumes:
   postgres_data: